[FKS-15] : Configure UI framework
fullstacksjs/the-charity-frontend pull request #4
Opened 2022-09-02 13:57 UTC by erfan-goodarzi

Install and configure Mantine

2022-09-02 14:41 UTC, ASafaeirad commented
Please fix the merge conflicts.

2022-09-03 09:30 UTC, AmirabbasJ requested changes

2022-09-03 09:30 UTC, AmirabbasJ commented on src/main.tsx
> +      }}
can't we omit this field?
is it required?

2022-09-03 09:30 UTC, AmirabbasJ commented on src/main.tsx
> +          colorScheme: 'light',
I think it's a better idea to have separate file for this
and why is `!important` there

2022-09-03 09:36 UTC, AmirabbasJ commented on src/main.tsx
> +      }}
then I'd say we remove the log and just make an empty function (maybe put a `NOTE` comment on it saying its required)
and if eslint has problem with empty function just ignore it with eslint ignore comment

2022-09-03 12:37 UTC, AmirabbasJ commented on src/main.tsx
> +      }}
in this case, no

2022-09-03 14:52 UTC, ASafaeirad requested changes

2022-09-03 14:52 UTC, ASafaeirad commented on src/main.tsx
> +      }}
We don't need dynamic color schemes in this app. Let's remove it.

2022-09-03 19:06 UTC, ASafaeirad approved these changes

2022-09-03 19:57 UTC, AmirabbasJ approved these changes

2022-09-03 19:59 UTC, merged