[FS-180]: List Of Projects API Integration
fullstacksjs/the-charity-frontend pull request #70
Opened 2023-01-04 12:43 UTC by erfan-goodarzi

This PR lists Project API integration.

2023-01-04 14:29 UTC, AmirabbasJ commented on src/components/CreateProject/ProjectForm/CreateProjectForm.tsx
> +        console.log(prevProjects, newProject)
we don't need the log

2023-01-04 14:29 UTC, AmirabbasJ commented on src/components/ProjectList/ProjectTable/ProjectTable.tsx
> +import { useProjectListQuery } from '../../../data-layer/operations/__generated__/typesAndHooks';
you should export `useProjectListQuery` in data-layer and please import it from `'@camp/data-layer'`

2023-01-04 14:29 UTC, AmirabbasJ commented on src/components/ProjectList/ProjectTable/ProjectTable.tsx
> +  const { data, loading, error, refetch } = useProjectListQuery()
refetch is unused you can remove it

2023-01-05 08:48 UTC, erfan-goodarzi commented on src/components/ProjectList/ProjectTable/ProjectTable.tsx
> +  if (loading) return <h1>loading...</h1>;
U need to use `<FullPageLoader/>` component here.

2023-01-06 19:17 UTC, ASafaeirad requested changes

2023-01-06 19:17 UTC, ASafaeirad commented on src/components/CreateProject/ProjectForm/CreateProjectForm.tsx
> +    },
This is the data layer's concern, let's keep it for now but we should move it there later.

2023-01-06 19:17 UTC, ASafaeirad commented on src/components/ProjectList/ProjectTable/ProjectTable.tsx
> +  if (error) console.log(error);
It's better to return a JSX here to not continue.

2023-01-26 18:25 UTC, ASafaeirad approved these changes

2023-01-26 18:25 UTC, merged