[FS-183]: Create A Member Form
fullstacksjs/the-charity-frontend pull request #87
Opened 2023-03-15 15:47 UTC by AmirabbasJ

This PR creates a member form.

2023-03-16 07:03 UTC, erfan-goodarzi requested changes

2023-03-16 07:03 UTC, erfan-goodarzi commented on libs/design/theme/theme.ts
> +          color: colors.fgSubtle,
Bro, u shouldn't write this style globally. cause it changes the `CreateFamily` and `CreateProject` input styles.

2023-03-16 07:04 UTC, erfan-goodarzi requested changes

2023-03-16 07:04 UTC, erfan-goodarzi commented on app/components/HouseholderForm/HouseholderIdentityForm.tsx
U need to undo it here.

2023-03-16 07:13 UTC, erfan-goodarzi commented on app/components/MemberForm/MemberForm.tsx
> +import { memberFormIds } from './MemberForm.ids';
Why not `memberFormIds as Ids`?

2023-03-21 06:33 UTC, ASafaeirad approved these changes

2023-03-21 06:34 UTC, merged