feat: add cspell persian dictionary
fullstacksjs/the-charity-frontend pull request #91
Opened 2023-04-16 00:15 UTC by mahdi-sheibak

Add this dictionary: https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/fa_IR

Vscode Extension: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-persian

2023-04-16 10:13 UTC, ASafaeirad requested changes

2023-04-16 10:13 UTC, ASafaeirad commented on app/messages.ts
> +          `مشکلی در مرحله آپدیت سرپرستی ای با نام "${name}" .ب وجود آمده است. لطفا دوباره تلاش کنید`,
It should be "به وجود آمده است"

2023-04-17 16:13 UTC, mahdi-sheibak commented
I see that CI/chromatic and CI/cypress-run have failed. Do they require my attention?
@ASafaeirad

2023-05-05 16:23 UTC, ASafaeirad commented
> I see that CI/chromatic and CI/cypress-run have failed. Do they require my attention? @ASafaeirad

@mahdi-sheibak 

Yes, there were some issues with the pipeline, can you rebase with the dev branch? that should fix the problem.

2023-05-07 09:03 UTC, ASafaeirad approved these changes

2023-05-07 10:48 UTC, merged