[FS-200]: Delete Family Api Integration
fullstacksjs/the-charity-frontend pull request #92
Opened 2023-05-04 17:14 UTC by erfan-goodarzi

2023-05-04 17:23 UTC, erfan-goodarzi commented
@ASafaeirad @AmirabbasJ 
Guys, we have duplication in the `FamilyDetail` and `FamilyTableRow` files. what do u think? what's ur suggestions?

2023-05-05 07:28 UTC, ASafaeirad commented
> @ASafaeirad @AmirabbasJ Guys, we have duplication in the `FamilyDetail` and `FamilyTableRow` files. what do u think? what's ur suggestions?

What part is duplicated?

2023-05-05 07:44 UTC, erfan-goodarzi commented on app/pages/Dashboard/Families/FamilyDetail/FamilyDetail.tsx
> +                  try {
@ASafaeirad here.

2023-05-05 07:44 UTC, erfan-goodarzi commented on app/components/FamilyList/FamilyTableRow.tsx
> +                  try {
@ASafaeirad And here.

2023-05-05 07:46 UTC, erfan-goodarzi commented on app/components/FamilyList/FamilyTableRow.tsx
> +                  try {
@ASafaeirad And here.

2023-05-05 17:34 UTC, ASafaeirad requested changes

2023-05-05 17:34 UTC, ASafaeirad commented on app/components/DeleteFamilyModal/DeleteFamilyModal.tsx
> +interface DeleteFamilyModalProps {
```suggestion
interface Props {
```

2023-05-05 17:34 UTC, ASafaeirad commented on app/components/DeleteFamilyModal/DeleteFamilyModal.tsx
> +}: DeleteFamilyModalProps) =>
```suggestion
}: Props) =>
```

2023-05-05 17:34 UTC, ASafaeirad commented on app/components/DeleteFamilyModal/DeleteFamilyModal.tsx
> +  onDeleteFamily: () => void;
```suggestion
  onDeleteFamily: VoidFunction;
```

2023-05-05 17:34 UTC, ASafaeirad commented on app/components/FamilyList/FamilyTableRow.tsx
> +                      message: t.notification.successfulDeleted(
`t.notification.delete.success` is a better name

2023-05-05 17:34 UTC, ASafaeirad commented on app/components/FamilyList/FamilyTableRow.tsx
> +                      message: t.notification.failedDeleted(name),
`t.notification.delete.failed` is a better name

2023-05-05 17:34 UTC, ASafaeirad commented on app/messages.ts
> +              `خانواده ی “${name}” با موفقیت حذف شد.`,
خانوار "name" با موفقیت حذف شد.

2023-05-05 17:34 UTC, ASafaeirad commented on app/messages.ts
> +              `مشکلی در مرحله حذف خانواده ی "${name}" بوجود آمده است. لطفا دوباره تلاش کنید.`,
* خانوار

2023-05-05 17:34 UTC, ASafaeirad commented on libs/data-layer/operations/mutations/useDeleteFamilyMutation.ts
> +    ? undefined
variables should not be null. please improve the type

2023-05-05 17:34 UTC, ASafaeirad commented on libs/data-layer/operations/mutations/useDeleteFamilyMutation.ts
> +  >,
Please update this type regarding the latest PR.
We've created a new type for mutation options.

2023-05-07 10:49 UTC, ASafaeirad approved these changes

2023-05-07 10:52 UTC, merged